### ISSUE TITLE
Error w/ package install & launch

### ISSUE THREAD

**Issue by ma-gh** [antonio-hickey/QG-Terminal#1]
Hi, interested in your project!

I tried to `pip install -r requirements.txt` and was thrown errors installing pandas. 

I then had to install the following packages manually:

- pandas
- dash
- dash_bootstrap_components

Then, upon running `python3 index.py`, I received the following error:

Traceback (most recent call last):
  File "index.py", line 8, in <module>
    from apps import home, esChain, usRates, portfolio, soma
  File "/home/ma/gits/gh/QG-Terminal/apps/esChain.py", line 342, in <module>
    greeks_(df2, columns=['Put Vega'])
  File "/home/ma/gits/gh/QG-Terminal/apps/esChain.py", line 315, in greeks_
    ranges = [
  File "/home/ma/gits/gh/QG-Terminal/apps/esChain.py", line 316, in <listcomp>
    ((df2_max - df2_min) * i) + df2_min
TypeError: unsupported operand type(s) for -: 'str' and 'str'

Python 3.8.5

-ma

**Comment by ma-gh** [comment]
Update:

I installed Python 3.7.0, created a venv, and ran the requirements list.

I had to manually `pip install`:
- dash==1.20.0
- dash_bootstrap_components
- plotly.express
- colorlover

Once I did that, when I ran `python3.7 index.py`, the console showed:

> Dash is running on http://127.0.0.1:8050/
> 
>  * Serving Flask app 'app' (lazy loading)
>  * Environment: production
>    WARNING: This is a development server. Do not use it in a production deployment.
>    Use a production WSGI server instead.
>  * Debug mode: on
> 

Upon going to `http://127.0.0.1:8050/`, the website reads "404".

**Comment by antonio-hickey** [comment]
Hello, I'm glad to see you found an interest in this projects i have some big updates coming soon it's still very rough draft at the moment. As to your issue, i think i have a solution:

So by default Flask will print out:
`Running on http://127.0.0.1:8050/` 

But this app's location is actually:
`http://127.0.0.1:8050/apps/home`

What i will do to make it easier is try to move the home page to the default flask server location for a more seamless experience. Hope this helps, thanks for checking it out.

**Comment by ma-gh** [comment]
Yes its interesting. Thanks for your reply. Feel free to contact me directly if you want specific feedback.
